version: '3.9'
networks:
  iservices:
    external:
      name: TrackingServices
services:
  web_app:
    build: ./web_app
      #context: ../
      #dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      iservices:
        aliases:
          - tracking-backend
    container_name: web_app
    hostname: web_app
    command: ["python3", "run.py"]
    depends_on:
      web_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - C:\Users\ssmyk\PycharmProjects\price_tracker\web_app:/web_app

  scraper_api:
    build: scraper_api
      #context: .
      #dockerfile: ./scraper_app/Dockerfile
    ports:
      - "5500:5500"
    networks:
      iservices:
        aliases:
          - tracking-scraper
    container_name: scraper_api
    hostname: scraper_api
    command: [ "python3", "run.py" ]
    depends_on:
      web_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - TZ=Europe/Warsaw
    #environment:
      #- PYTHONPATH=/scraper_app
    volumes:
      - C:\Users\ssmyk\PycharmProjects\price_tracker\scraper_api:/scraper_api
  worker:
    build: scraper_api
    #context: .
    #dockerfile: ./scraper_app/Dockerfile
    networks:
      iservices:
        aliases:
          - tracking-worker
    container_name: worker
    hostname: worker
    depends_on:
      web_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - TZ=Europe/Warsaw
    command: ['celery', '-A', 'app.scraper', 'worker', '-l', 'info']


  web_db:
    image: postgres:14
    container_name: web_db
    hostname: web_db
    ports:
      - "5433:5432"
    networks:
      iservices:
        aliases:
          - tracking-db-backend
    environment:
      #- POSTGRES_USER=price_tracker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=price_tracker
      - POSTGRES_INITDB_ARGS='--auth-host=scram-sha-256'
      - TZ=Europe/Warsaw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      iservices:
        aliases:
          - tracking-rabbitmq
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      - TZ=Europe/Warsaw



