version: '3.9'
networks:
  iservices:
    external:
      name: TrackingServices
services:
  web:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - "5000:5000"
    networks:
      iservices:
        aliases:
          - tracking-backend
    container_name: price_tracker
    hostname: price_tracker
    command: ["python3", "run.py"]
    depends_on:
      web_db:
        condition: service_healthy
    volumes:
      - pt:/pt
      - C:\Users\Sebastian\PycharmProjects\price_tracker:/app

    environment:
      FLASK_ENV: development

  web_db:
    image: postgres:14
    container_name: web_db
    hostname: web_db
    ports:
      - "5433:5432"
    networks:
      iservices:
        aliases:
          - tracking-db-backend
    environment:
      #- POSTGRES_USER=price_tracker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=price_tracker
      - POSTGRES_INITDB_ARGS='--auth-host=scram-sha-256'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always
volumes:
  pt:
    external: true
